version: '3'

services:
  db:
    hostname: nc_db
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PASSWORD: ${DATABASE_PWD}
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "15432:5432"

  redis:
    image: redis:alpine
    restart: always

  app:
    build: ./
    volumes:
      - nextcloud:/usr/src/nextcloud
    environment:
      - POSTGRES_HOST=${DATABASE_HOST}
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PWD}
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis

  cron:
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

  nc-web:
    container_name: nginx
    build:
      context: ./nginx
    environment:
      - VIRTUAL_HOST=cloud.example.localhost
      - LETSENCRYPT_HOST=letsencrypt-companion
      - LETSENCRYPT_EMAIL=foo@bar.com
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - nextcloud:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/logs:/var/log/nginx
      - ./nginx/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - app
    networks:
      - proxy-tier
      - default
    ports:
      - "8888:80"
      - "443:443"

  letsencrypt-companion:
    image: nginxproxy/acme-companion
    volumes:
      - ./nginx/certs:/etc/nginx/certs
      - acme:/etc/acme.sh
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy-tier
    depends_on:
      - nc-web

volumes:
  db:
  nextcloud:
  certs:
  acme:
  vhost.d:
  html:

networks:
  proxy-tier:
