version: "3.8"
services:
  nextcloud-db:
    hostname: nextcloud-db
    container_name: nextcloud-db
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PASSWORD: ${DATABASE_PWD}
    ports:
      - "16442:5442"

  nextcloud-redis:
    container_name: nextcloud-redis
    image: "redis:alpine"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6378:6379"
    env_file: .env
    hostname: nextcloud-redis
    restart: unless-stopped

  nextcloud-app:
    image: nextcloud:fpm
    container_name: nextcloud-app
    hostname: nextcloud-app
    restart: unless-stopped
    env_file: .env
    depends_on:
      - nextcloud-db
      - nextcloud-redis
    volumes:
      - ./nextcloud-data/:/var/www/html
      # Uncomment and specify your data directory (if you have a mounted hard drive)
      # !! ALWAYS make a backup of your data before such manipulations !!
      # - /path/to/data/directory:/var/www/html/data

  nextcloud-web:
    image: nginx:alpine
    container_name: nextcloud-web
    hostname: nextcloud-web
    restart: unless-stopped
    env_file: .env
    depends_on:
      - nextcloud-app
    volumes:
      - ./nextcloud-data/:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8888:80

  nextcloud-cron:
    image: nextcloud:fpm
    container_name: nextcloud-cron
    hostname: nextcloud-cron
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./nextcloud-data/:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - nextcloud-db
      - nextcloud-redis
